package com.tylerphelps.motormonitor;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.tylerphelps.motormonitor.SensorModule;
import com.tylerphelps.motormonitor.SensorDataEntry;

import com.tylerphelps.motormonitor.SensorModuleDao;
import com.tylerphelps.motormonitor.SensorDataEntryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sensorModuleDaoConfig;
    private final DaoConfig sensorDataEntryDaoConfig;

    private final SensorModuleDao sensorModuleDao;
    private final SensorDataEntryDao sensorDataEntryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sensorModuleDaoConfig = daoConfigMap.get(SensorModuleDao.class).clone();
        sensorModuleDaoConfig.initIdentityScope(type);

        sensorDataEntryDaoConfig = daoConfigMap.get(SensorDataEntryDao.class).clone();
        sensorDataEntryDaoConfig.initIdentityScope(type);

        sensorModuleDao = new SensorModuleDao(sensorModuleDaoConfig, this);
        sensorDataEntryDao = new SensorDataEntryDao(sensorDataEntryDaoConfig, this);

        registerDao(SensorModule.class, sensorModuleDao);
        registerDao(SensorDataEntry.class, sensorDataEntryDao);
    }
    
    public void clear() {
        sensorModuleDaoConfig.getIdentityScope().clear();
        sensorDataEntryDaoConfig.getIdentityScope().clear();
    }

    public SensorModuleDao getSensorModuleDao() {
        return sensorModuleDao;
    }

    public SensorDataEntryDao getSensorDataEntryDao() {
        return sensorDataEntryDao;
    }

}
