package com.tylerphelps.motormonitor;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "SENSOR_MODULE".
 */
public class SensorModule {

    private Long id;
    /** Not-null value. */
    private String access_name;
    /** Not-null value. */
    private String access_passcode;
    /** Not-null value. */
    private String viewable_name;
    private String details;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SensorModule() {
    }

    public SensorModule(Long id) {
        this.id = id;
    }

    public SensorModule(Long id, String access_name, String access_passcode, String viewable_name, String details) {
        this.id = id;
        this.access_name = access_name;
        this.access_passcode = access_passcode;
        this.viewable_name = viewable_name;
        this.details = details;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getAccess_name() {
        return access_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAccess_name(String access_name) {
        this.access_name = access_name;
    }

    /** Not-null value. */
    public String getAccess_passcode() {
        return access_passcode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAccess_passcode(String access_passcode) {
        this.access_passcode = access_passcode;
    }

    /** Not-null value. */
    public String getViewable_name() {
        return viewable_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setViewable_name(String viewable_name) {
        this.viewable_name = viewable_name;
    }

    public String getDetails() {
        return details;
    }

    public void setDetails(String details) {
        this.details = details;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
