package com.tylerphelps.motormonitor;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "SENSOR_DATA_ENTRY".
 */
public class SensorDataEntry {

    private Long id;
    /** Not-null value. */
    private String module_access_name;
    private java.util.Date date;
    private Double time;
    private Double vibration;
    private Double temperature;
    private Double current;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SensorDataEntry() {
    }

    public SensorDataEntry(Long id) {
        this.id = id;
    }

    public SensorDataEntry(Long id, String module_access_name, java.util.Date date, Double time, Double vibration, Double temperature, Double current) {
        this.id = id;
        this.module_access_name = module_access_name;
        this.date = date;
        this.time = time;
        this.vibration = vibration;
        this.temperature = temperature;
        this.current = current;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getModule_access_name() {
        return module_access_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setModule_access_name(String module_access_name) {
        this.module_access_name = module_access_name;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Double getTime() {
        return time;
    }

    public void setTime(Double time) {
        this.time = time;
    }

    public Double getVibration() {
        return vibration;
    }

    public void setVibration(Double vibration) {
        this.vibration = vibration;
    }

    public Double getTemperature() {
        return temperature;
    }

    public void setTemperature(Double temperature) {
        this.temperature = temperature;
    }

    public Double getCurrent() {
        return current;
    }

    public void setCurrent(Double current) {
        this.current = current;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
